### ISSUE TITLE
Cannot convert video

### ISSUE THREAD

**Issue by NitrousX** [ErraticFox/Telsar#2]
Hi erraticfox,
I tried your method that you mentioned on reddit.
Opened the newer version of Telsar that comes with ffmpeg included, and went to convert a mp4 video.
Selected the directory folder from the input menu and drop the output file to drop on the desktop.

Enabled the command screen by pressing crtl+s white box appears below,
![untitled-1](https://cloud.githubusercontent.com/assets/21369467/18142648/7552494a-6fb6-11e6-9085-505c133b1ca9.jpg)
 left every setting on default apart from changing file format to webm. Clicked submit nothing happens.

Tried changing the directory from library shortcuts to going direct to the root directory of selected files.
Tried different file names that are shorter still the same issue.

**Comment by ErraticFox** [comment]
What's you Hard Drives letter? It might be something to do with the directory, I highly doubt that though. Also, could you take a picture of the folder where you have Telsar?

**Comment by NitrousX** [comment]
my hard drive letter for the source was F and for the output drive letter was C directed to the desktop

**Comment by ErraticFox** [comment]
Are you starting the executable from the folder with all the files in it?

**Comment by NitrousX** [comment]
Yes I am the telsar.exe even tried running the application as administrator by righting clicking on the exe

**Comment by ErraticFox** [comment]
Have you tried multiple files?

**Comment by NitrousX** [comment]
Yes I have tried files from nvidia shadow play, xbox game dvr, videos downloaded from the internet and videos that I had created from adobe premiere exports

**Comment by ErraticFox** [comment]
Is FFMPEG still inside the folder? If so, do this: Open a command prompt inside that folder, then type `ffmpeg -h`. Does it give you a list of options?

**Comment by NitrousX** [comment]
within command prompt used ''cd'' command to the C:\Users\nitro\Downloads\Telsar-win32-x64-0.1.1-FFMPEG>ffmpeg -h doesnt work. Also tried C:\Users\nitro\Downloads\Telsar-win32-x64-0.1.1-FFMPEG>ffmpeg.exe -h that didn't work either. Attempting to open ffmpeg.exe it opens for a split sceond then exits again

**Comment by ErraticFox** [comment]
Is it just saying that `ffmpeg is not a command`? If so, you might want to download ffmpeg from their website and try doing the same thing. With you being open in cmd within the same folder as ffmpeg.exe, it should've said something.

**Comment by ErraticFox** [comment]
Haven't heard a reply in a bit. So if needs reopened, just ask.
